# Executive summary {#executive-summary}

## Background

Dr. Ariel Balter, an experienced scientist and data analyst, was diagnosed with ADHD and ASD very late in life and is also raising a teenager with both of these diagnoses. Dr. Balter's desire to use this new framework to help understand his life and career challenges led him to study the scientific literature on autism as well as non-scientific essays about neurodiversity. He found that both our scientific and social understanding of autism and other types of neurodivergence were going through rapid, seismic changes. Much of the change in the past decade came from autistic self-advocates, and especially autistic researchers putting themselves into the research process. These changes have led to controversies and arguments that are still unfolding and will take time to resolve. However, it is indisputable that a number of facts about autism in adulthood have caught society off guard:

1.  Most autistic people are [[not intellectually disabled]{.underline}](https://www.thetransmitter.org/spectrum/the-blurred-line-between-autism-and-intellectual-disability/?fspec=1). But navigating society feels like being a left-handed person using right-handed scissors: difficult and unwieldy at best.

2.  Being autistic is how you are born, and you stay that way for your whole life. Therefore, there are roughly the same percentage of autistic adults as children.

3.  We know very little about autistic adults who aren't intellectually disabled and how life has impacted them. Almost all research and services have focused on children and intellectually disabled adults.

4.  Oregon likely has between 75,000 and 150,000 autistic adults. A small fraction of them receive disability services. A large and unknown fraction are enduring unnecessary negative life experiences.

Because autism presents as a constellation of traits rather than a linear spectrum of abilities, most autistic adults are able to perform the [[activities of daily living]{.underline}](https://www.cms.gov/research-statistics-data-and-systems/research/mcbs/downloads/2008_appendix_b.pdf) (ADLs) independently, but often at a great cost to their emotional well-being. The unique challenges we face do not check the boxes in Oregon's Department of Intellectual and Developmental Disabilities (I/DD) assessments. But they are real.

In the Winter of 2023, Dr. Balter started attending local support groups for autistic adults and participating in online communities. He was struck by the level of unmet need he was hearing about from his many peers---people who have skills, education, and abilities but nonetheless are struggling due to common challenges navigating a neurotypical world. Some of these challenges arise from societal factors that will only change over decades through persistent advocacy work. Others simply reflected breakdowns of existing systems (healthcare, employment, social service) largely due to misinformation or lack of information. He began doing some root cause analysis and founded Autism All Grown Up along with some of the amazing people he met.

## Goals

We are naming the organization Autism All Grown Up (AAGU) in part because of the way people tend to use that phrase when they meet someone whom they had only known as a child and find themselves struck by how different the adult person in front of them is from the picture of the child they had carried around in their head. Calling ourselves a Nexus refers to how we envision our organization integrating into the universe comprised of autistic adults in Oregon and the various organizations, programs, services, and providers they interact with. Most social organizations are hubs, which means they are locations that take in money along some channels and provide services or information outward along other channels. AAGU will activate and empower the autistic community and autism-focused organizations by improving and building channels of communication and bodies of information they need.

This project will combine a long-term strategy with immediate action. There are many things we can do and are doing immediately, such as building relationships, creating information products, and launching The Uncommons (reference). Other goals will take time.

Our work is already helping autistic adults find and use the services they need and helping others better understand the needs of autistic adults. We are ready to start autistic-friendly meeting and coworking spaces called *The Uncommons*, where people can safely unmask, mingle, and collaborate authentically. We are working with local organizations to create better information for and about autistic medical needs. We are seeking out programs and organizations that exist but are not widely known about and working to connect these organizations to potential clients and to each other. We have been invited to participate in a data analysis working group sponsored by the Oregon Commission on Autism Spectrum Disorder.

## Growth Plan

We plan to build out our capability in phases through funding and continued in-kind donations, with a low emphasis on volunteer work. Dr. Balter strongly believes that AAGU should be staffed by autistic people earning a market wage. Our current model proposes a 10% overhead for our parent organization to cover certain executive and business services.

**Initial Weeks: Seed (Startup phase)\
**Budget: \$2,310/week, Effort: 1.5 FTE

-   Set up organization structure

-   Solicit funds for *Sprout* phase (crowdfunding, donations, small grants)

-   Establish partnerships and presence in the community

**Weeks 1-8: Sprout (Establishing the project)\
**Budget: \$33,600, Effort: 2.75 FTE

-   Continue the work we have been doing:

    -   The Uncommons

    -   Informational materials

    -   Building community and connections

-   Define our capabilities

-   Identify large funding opportunities

-   Build relationships, find partnerships, solicit contracts

**Weeks 9-26: Grow (Achieving Maturity)**

Budget: \$117,612.00, Effort: 4.25 FTE

-   Continue ongoing work

-   Market and expand *The Uncommons*

-   Apply for large grants and contracts

-   Build our information infrastructure

    -   Databases

    -   Expertise

-   Build our communication infrastructure

    -   Website

    -   Information products

    -   Podcasts, talks, lectures

#  
