# Funding {#funding}

We are poised to launch a GoFundMe crowdsource campaign as soon as we have our nonprofit status confirmed by ARRO. We hope to raise seed money of \$2k-\$3k per week to jump start formal operations \*\*\*\*\*\*\*\*\*\*\*\*\* next \$34k for our 8-week Sprout phase. We hope to launch the Sprout phase within our first month.

A key element of our first 8 weeks of formal operation (Sprout) will be to create a calendar of funding deadlines and communicate with funders to prioritize our initial grant-writing efforts. It will also be crucial that we complete the [[initial projects we have started]{.underline}](#what-we-have-started) during the Sprout phase so we can demonstrate our effectiveness to potential supporters. At the end of the Sprout phase we will report to our umbrella organizations and all funders/sponsors.

We have already identified almost 100 grants and sponsorships for which we meet the basic requirements. These include grants from the State of Oregon (e.g. Oregon Health Authority), Oregon healthcare companies (Legacy, Pacific Source, Cambia, etc.), and a mixture of private and public foundations and trusts. We have missed the 2024 funding cycle for some of these, but many have multiple cycles per year or do not run in cycles. Some of these are small pots of money and others regularly award hundred of thousands of dollars. We will also collect sliding-scale fees for using The Uncommons co-working spaces.

During our Grow phase, we hope to show that we can collect, analyse, and disseminate information for and about the adult autistic community with a very high level of capacity and efficiency. We hope this expertise will enable us to secure outside contracts as subject matter experts, analysts, and report writers, which will provide yet another avenue for revenue. We will complete the Grow phase with a report to our umbrella organization and our financial supporters.
