# Appendix 3: Potential Funders

## Healthcare Corporations

| Or ganiz ation                    | Pr oduct                                                    | Links                                                                                                                                                                                                                                                                                                                                                                                             |
|:-------------|:-------------|:--------------------------------------------|
| Adve ntist                        | S ponso rship Re quest                                      | [[https://hi paa-submit.jotform.com/221594871753061]{.underline}](https://hipaa-submit.jotform.com/221594871753061)                                                                                                                                                                                                                                                                               |
| Adve ntist                        | Comm unity Be nefit                                         | [[https://adventisthealth.org/portland/about -us/community-benefit/]{.underline}](https://advent%20isthealth.org/portland/about-us/community-benefit/)                                                                                                                                                                                                                                            |
| C ambia                           | He althy and Conn ected Aging                               | [[https://www.cambiahealthfound ation.org/focus-areas/healthy-and-connected-aging.h tml]{.underline}](https://www.cambiahealthfoundatio%20n.org/focus-areas/healthy-and-connected-aging.html)                                                                                                                                                                                                     |
| C ambia                           | S ponso rship                                               | [\[https://www.cambiahealthfoundation.org/applicant- resources/current-funding-opportunities.html\]{.unde rline}](https://www.cambiahealthfoundation.org/appl%20icant-resources/current-funding-opportunities.html)                                                                                                                                                                               |
| CareO regon                       | Comm unity G iving g rants and sp onsor ships               | [[https://www.careoregon.org/community/co mmunity-giving-grants-for-nonprofit-organizations]{.underline}](https://www.careoregon.org/community/c%20ommunity-giving-grants-for-nonprofit-organizations)                                                                                                                                                                                            |
| CareO regon                       | HRSN Ser vices                                              | [re quest.social.determinants\@careoregon.org](mailto:r%20equest.social.determinants@careoregon.org){.email},                                                                                                                                                                                                                                                                                     |
| H ealth Share                     | S ponso rship                                               | [[https://www.heal thshareoregon.org/about/sponsorship]{.underline}](h%20ttps://www.healthshareoregon.org/about/sponsorship)                                                                                                                                                                                                                                                                      |
| H ealth Share                     | HRSN Ser vices                                              | [[https://www.healthshareorego n.org/community-partners/hrsn]{.underline}](https:/%20/www.healthshareoregon.org/community-partners/hrsn)                                                                                                                                                                                                                                                          |
| H ealth Share                     | HRSN Ser vices                                              | [[https://health-share-or.portals.zen ginehq.com/program/community-capacity-building/info]{.underline}](https://health-share-or.portals.zeng%20inehq.com/program/community-capacity-building/info)                                                                                                                                                                                                |
| K aiser                           | HRSN Ser vices                                              | [Laura.J.Ho ward\@kp.org](mailto:Laura.J.Howard@kp.org){.email}                                                                                                                                                                                                                                                                                                                                   |
| K aiser                           | HRSN Ser vices                                              | [\[https://communityhealth-midatlantic.kaiserper manente.org/improving-communities/grantmaking/\]{.un derline}](https://communityhealth-midatlantic.kaise%20rpermanente.org/improving-communities/grantmaking/)                                                                                                                                                                                   |
| K aiser                           | HRSN Ser vices                                              | [[https://communityhealth-midatlantic.kaiserpermanen te.org/wp-content/uploads/2024/02/LOI-Submitter-Hel p-Document_508.pdf]{.underline}](https://communityh%20ealth-midatlantic.kaiserpermanente.org/wp-content/u%20ploads/2024/02/LOI-Submitter-Help-Document_508.pdf)                                                                                                                          |
| K aiser                           | HRSN Ser vices                                              | [MedicaidHRSflexfunds\@ kp.org](mailto:MedicaidHRSflexfunds@kp.org){.email}                                                                                                                                                                                                                                                                                                                       |
| K aiser                           | Comm unity Be nefit                                         | [community.benefi t\@kp.org](mailto:community.benefit@kp.org){.email}                                                                                                                                                                                                                                                                                                                             |
| L egacy                           | Comm unity H ealth Grant                                    | [[https://www.legacyhealth.org/Givi ng-and-Support/community-engagement/Community-Grant s]{.underline}](https://www.legacyhealth.org/Giving%20-and-Support/community-engagement/Community-Grants)                                                                                                                                                                                                 |
| L egacy                           | L egacy Res earch Inst itute                                | [\[ht tps://www.legacyhealth.org/For-Health-Professionals /legacy-research-institute/services/grants\]{.underl ine}](https://www.legacyhealth.org/For-Health-Profe%20ssionals/legacy-research-institute/services/grants)                                                                                                                                                                          |
| L egacy                           | S ponso rship                                               | [[https://www.legacyhealth. org/Giving-and-Support/community-engagement/Sponsor ships]{.underline}](https://www.legacyhealth.org/Gi%20ving-and-Support/community-engagement/Sponsorships)                                                                                                                                                                                                         |
| L egacy                           | HRSN Ser vices                                              | [HealthRelatedServices\@pacificsource.com](mail%20to:HealthRelatedServices@pacificsource.com){.email}                                                                                                                                                                                                                                                                                             |
| Ochin                             |                                                             |                                                                                                                                                                                                                                                                                                                                                                                                   |
| OHSU                              | Comm unity P artne rship Pr ogram                           | [[https://www.ohsu.edu/knig ht-cancer-institute/community-partnership-program-g rants]{.underline}](https://www.ohsu.edu/knight-can%20cer-institute/community-partnership-program-grants)                                                                                                                                                                                                         |
| OHSU                              | Comm unity P artne rship Pr ogram                           | [[htt ps://www.ohsu.edu/knight-cancer-institute/how-apply -community-grant]{.underline}](https://www.ohsu.edu%20/knight-cancer-institute/how-apply-community-grant)                                                                                                                                                                                                                               |
| OHSU                              | Comm unity P artne rship Pr ogram                           | [[https://www.ohsu.edu/sites/ default/files/2024-01/CPP_RFP_2024.1_FINAL_lowres_0 .pdf]{.underline}](https://www.ohsu.edu/sites/defau%20lt/files/2024-01/CPP_RFP_2024.1_FINAL_lowres_0.pdf)                                                                                                                                                                                                       |
| OHSU                              | T iered G rants                                             | [[https://www.ohsu.edu/knight-ca ncer-institute/tiered-grants]{.underline}](https://%20www.ohsu.edu/knight-cancer-institute/tiered-grants)                                                                                                                                                                                                                                                        |
| OHSU                              | HRSN Ser vices                                              | [\[https://www.ohsu.edu/health-services\] {.underline}](https://www.ohsu.edu/health-services)                                                                                                                                                                                                                                                                                                     |
| OHSU                              | Rural Popul ation H ealth Incu bator Pr ogram               | [\[https://www.ohsu.edu/oregon-office-of-rural-hea lth/rural-population-health-incubator-program\]{.und erline}](https://www.ohsu.edu/oregon-office-of-rura%20l-health/rural-population-health-incubator-program)                                                                                                                                                                                 |
| Pa cific S ource                  | Comm unity H ealth Excel lence G rants                      | [[https://pacificsource.com /sites/default/files/2023-02/PRV510_0123_CHE%20Flie r.pdf]{.underline}](https://pacificsource.com/sites%20/default/files/2023-02/PRV510_0123_CHE%20Flier.pdf)                                                                                                                                                                                                         |
| Pa cific S ource                  | Comm unity Ca pacit y-Bui lding Fu nding for HRSN ser vices | [[https://pacificsource.com/art icle/community-capacity-building-funding-hrsn-servi ces]{.underline}](https://pacificsource.com/article%20/community-capacity-building-funding-hrsn-services)                                                                                                                                                                                                     |
| Pa cific S ource                  | Comm unity H ealth Excel lence G rants                      | [\[ht tps://www.ruralhealthinfo.org/funding/5469\]{.underl ine}](https://www.ruralhealthinfo.org/funding/5469)                                                                                                                                                                                                                                                                                    |
| Pa cific S ource                  | All                                                         | [[https://pacificsource.com/sites/default/fi les/2023-08/CLB1330_0823_PacificSource%20Funding%20 Navigation%20Guide.pdf]{.underline}](https://pacifi%20csource.com/sites/default/files/2023-08/CLB1330_082%203_PacificSource%20Funding%20Navigation%20Guide.pdf)                                                                                                                                  |
| Pa cific S ource                  | Pac ificS ource Found ation for H ealth I mprov ement       | [[https://pacificsource.com/community/foundation?utm \_source=pdf&utm_medium=flier&utm_campaign=FundingGu ide&utm_id=CLB1330]{.underline}](https://pacificsou%20rce.com/community/foundation?utm_source=pdf&utm_med%20ium=flier&utm_campaign=FundingGuide&utm_id=CLB1330)                                                                                                                         |
| Pa cific S ource                  | He althy C ommun ities Pr ogram                             | [\[http://www.grantinterface.com/Home/Logon\]{.un derline}](http://www.grantinterface.com/Home/Logon)                                                                                                                                                                                                                                                                                             |
| Provi dence                       | Comm unity G rants /Dona tions                              | [[https://www.p rovidence.org/locations/wa/providence-regional-medi cal-center-everett/donate-and-volunteer/community-s ponsorships]{.underline}](https://www.providence.or%20g/locations/wa/providence-regional-medical-center-e%20verett/donate-and-volunteer/community-sponsorships)                                                                                                           |
| Provi dence                       | S ponso rship                                               | [[https://webportalapp.com/sp/logi n/prmce-sponsor-application]{.underline}](https://w%20ebportalapp.com/sp/login/prmce-sponsor-application)                                                                                                                                                                                                                                                      |
| Provi dence                       | HRSN Ser vices                                              | [HRSNBenefit\@Provide nce.org](mailto:HRSNBenefit@Providence.org){.email}                                                                                                                                                                                                                                                                                                                         |
| Tri llium                         | Comm unity Be nefit I nitia tives                           | [[https://www.p rnewswire.com/news-releases/trillium-community-heal th-plan-announces-request-for-applications-for-2023 -small-grants-for-community-benefit-initiatives-301 845411.html]{.underline}](https://www.prnewswire.co%20m/news-releases/trillium-community-health-plan-anno%20unces-request-for-applications-for-2023-small-grant%20s-for-community-benefit-initiatives-301845411.html) |
| Tri llium                         | Comm unity Be nefit I nitia tives                           | [\[https://www.trilliumohp.com/supporting-oregon-c ommunities/community-benefit-initiatives.html\]{.und erline}](https://www.trilliumohp.com/supporting-ore%20gon-communities/community-benefit-initiatives.html)                                                                                                                                                                                 |
| Tri llium                         | Comm unity Cap acity Bui lding Fu nding                     | [[https://www.t rilliumohp.com/supporting-oregon-communities/health -related-social-needs/community-capacity-building-f unding.html]{.underline}](https://www.trilliumohp.c%20om/supporting-oregon-communities/health-related-soc%20ial-needs/community-capacity-building-funding.html)                                                                                                           |
| Ce ntral O regon H ealth Co uncil | Sta ndard G rants                                           | [\[ht tps://cohealthcouncil.org/standard-grants/\]{.underl ine}](https://cohealthcouncil.org/standard-grants/)                                                                                                                                                                                                                                                                                    |
|                                   | Mini G rants                                                | [\[https://cohealthcouncil.org/mini-grants/\]{.un derline}](https://cohealthcouncil.org/mini-grants/)                                                                                                                                                                                                                                                                                             |
| St Ch arles H ealth S ystem       | Comm unity Be nefit G rants and Sp onsor ships              | [\[ https://www.stcharleshealthcare.org/community-healt h/community-benefit-grants-and-sponsorships\]{.under line}](https://www.stcharleshealthcare.org/communit%20y-health/community-benefit-grants-and-sponsorships)                                                                                                                                                                            |

## State Agencies

| Entity                   | P roduct                             | Links                                                                                                                                                                                                                                                                                 |
|:-------------|:-------------|:--------------------------------------------|
| Oregon Health Aut hority | Block Grants                         | [[https://www.oregon.gov/oha/hsd/amhpac/page s/block-grants.aspx]{.underline}](https://www.or%20egon.gov/oha/hsd/amhpac/pages/block-grants.aspx)                                                                                                                                      |
| Oregon Health Aut hority | Com munity Ca pacity Bu ilding Funds | [[https://www.oregon.gov/oha/hsd/medicaid-poli cy/pages/ccbf.aspx]{.underline}](https://www.ore%20gon.gov/oha/hsd/medicaid-policy/pages/ccbf.aspx)                                                                                                                                    |
| Oregon Health Aut hority | Com munity Ca pacity Bu ilding Funds | [[https://content.govdelivery.com/accounts/ORHA/ bulletins/38e15e8]{.underline}](https://content.%20govdelivery.com/accounts/ORHA/bulletins/38e15e8)                                                                                                                                  |
| Oregon Health Aut hority | SHARE Init iative                    | [[https://www.oregon.gov/oha/h pa/dsi-tc/pages/share.aspx]{.underline}](https:/%20/www.oregon.gov/oha/hpa/dsi-tc/pages/share.aspx)                                                                                                                                                    |
| Oregon Health Aut hority | PUBLIC HEALTH EQUITY                 | <https://www.oregon.gov/oha/PH/ABOUT/MODCE> T%20CBO%20Documents/PH%20Equity%20CBO%20Fiscal%2 0Guidance%20-%20AY25%20%20DRAFT-%2002.28.24.pdf\>                                                                                                                                        |
| Oregon Health Aut hority | PUBLIC HEALTH EQUITY                 | [[https://content.govdelivery.com/accounts/ORHA/ bulletins/37611cc]{.underline}](https://content.%20govdelivery.com/accounts/ORHA/bulletins/37611cc)                                                                                                                                  |
| Oregon Health Aut hority | GRANT                                | [[https://www.oregon.gov/oha /ph/healthypeoplefamilies/youth/healthschool/sch oolbasedhealthcenters/pages/mh-expansion-grant.a spx]{.underline}](https://www.oregon.gov/oha/ph/%20healthypeoplefamilies/youth/healthschool/schoolb%20asedhealthcenters/pages/mh-expansion-grant.aspx) |
| Oregon Health Aut hority | HTO CHIP P roject Grants             | [[https://www.oregon .gov/oha/PH/ABOUT/Documents/HTO%20CHIP%202024%20 FAQ.pdf]{.underline}](https://www.oregon.gov/oha%20/PH/ABOUT/Documents/HTO%20CHIP%202024%20FAQ.pdf)                                                                                                             |
| Oregon State             | I MPACTS Grant P rogram              | [[https://ww w.oregon.gov/cjc/impacts/Documents/2020_IMPACTSO nePager.pdf]{.underline}](https://www.oregon.gov%20/cjc/impacts/Documents/2020_IMPACTSOnePager.pdf)                                                                                                                     |

## Foundations and Trusts

| Foun dation                      | P roduct                                         | Links                                                                                                                                                                                                                                        |
|:--------------|:--------------|:------------------------------------------|
| Car penter Foun dation           | Grant                                            | [[http://carpenter-foundation.or g/]{.underline}](http://carpenter-foundation.org/)                                                                                                                                                          |
| Anna May Family Foun dation      | Grant                                            | [[http://www.a nnamay.org/]{.underline}](http://www.annamay.org/)                                                                                                                                                                            |
| Gordon Elwood Foun dation        | Grant                                            | [\[http s://www.gordonelwoodfoundation.org/index\]{.underli ne}](https://www.gordonelwoodfoundation.org/index)                                                                                                                               |
| Ma ybelle Clark Mac donald Fund  | Grant                                            | [[https://mcmfundgiving.org/grants /]{.underline}](https://mcmfundgiving.org/grants/)                                                                                                                                                        |
| M J M urdock Char itable Trust   | STR ATEGIC GRANT                                 | [[https://murdocktru st.org/grant-application-process/]{.underline}](ht%20tps://murdocktrust.org/grant-application-process/)                                                                                                                 |
| C ollins Foun dation             | Resp onsive Grant                                | [[https://www.collinsfou ndation.org/responsive-grantmaking-submission-guid elines]{.underline}](https://www.collinsfoundation%20.org/responsive-grantmaking-submission-guidelines)                                                          |
| C ollins Foun dation             | Resp onsive Grant                                | [[https://www.collinsfoundat ion.org/responsive-grantmaking-submission-guidelin es/frequently-asked-questions]{.underline}](https:%20//www.collinsfoundation.org/responsive-grantmaking%20-submission-guidelines/frequently-asked-questions) |
| Benton Com munity Foun dation    | Com munity Grants                                | [[https://bcfgives .org/wp-content/uploads/2024/02/2023-Full-Grant-Hi story.pdf]{.underline}](https://bcfgives.org/wp-co%20ntent/uploads/2024/02/2023-Full-Grant-History.pdf)                                                                |
| Reser Family Foun dation         | Resp onsive Grant Pr ograms                      | [[https://thereserfamilyfoun dation.org/apply-for-a-grant/]{.underline}](https:%20//thereserfamilyfoundation.org/apply-for-a-grant/)                                                                                                         |
| Foster Foun dation               | Grant                                            | [\[ht tp://www.thefosterfoundation.org/Home.htm\]{.underl ine}](http://www.thefosterfoundation.org/Home.htm)                                                                                                                                 |
| Doug Flutie Foun dation          | Autism Com munity Impact Grant                   | [[https://flutiefoundation .org/helping-communities/autism-community-impact-g rant/]{.underline}](https://flutiefoundation.org/h%20elping-communities/autism-community-impact-grant/)                                                        |
| Doug Flutie Foun dation          | Flutie F ellows -- Career and Life Goal S upport | [\[ht tps://flutiefoundation.org/helping-individuals/flu tie-fellows-career-and-life-goal-support/\]{.underl ine}](https://flutiefoundation.org/helping-individ%20uals/flutie-fellows-career-and-life-goal-support/)                         |
| Doug Flutie Foun dation          | Fin ancial Relief for Fa milies                  | [[https:// flutiefoundation.org/helping-families/direct-finan cial-support/]{.underline}](https://flutiefoundati%20on.org/helping-families/direct-financial-support/)                                                                        |
| Ch ambers Family Foun dation     | Grant                                            | [[https://www.chambers familyfoundation.com/submissions]{.underline}](htt%20ps://www.chambersfamilyfoundation.com/submissions)                                                                                                               |
| Meyer Me morial Trust            | Grant                                            | [[https://mmt.org/]{.underline}](https://mmt.org/)                                                                                                                                                                                           |
| Ben B Cheney Foun dation         | Grant                                            | [\[https://www.benbcheneyfoundation.org/\]{. underline}](https://www.benbcheneyfoundation.org/)                                                                                                                                              |
| Autzen Foun dation               | Grant                                            | [\[ https://www.autzenfoundation.org/deadlines\]{.under line}](https://www.autzenfoundation.org/deadlines)                                                                                                                                   |
| Oregon Com munity Foun dation    | Grant                                            | [[https://oregoncf.org /grants-and-scholarships/grants/]{.underline}](htt%20ps://oregoncf.org/grants-and-scholarships/grants/)                                                                                                               |
| Robert Wood J ohnson Foun dation | Mu ltiple                                        | [\[https://www.rwjf.org/en/grants.html\] {.underline}](https://www.rwjf.org/en/grants.html)                                                                                                                                                  |
| Robert Wood J ohnson Foun dation | Mu ltiple                                        | [[https://www. rwjf.org/en/grants/active-funding-opportunities.ht ml?o=1&us=1]{.underline}](https://www.rwjf.org/en/%20grants/active-funding-opportunities.html?o=1&us=1)                                                                    |
| Weyer houser                     | Giving Fund                                      | [[ht tps://www.weyerhaeuser.com/company/values/citizens hip/giving-fund/]{.underline}](https://www.weyerha%20euser.com/company/values/citizenship/giving-fund/)                                                                              |

# 
