# Appendix 2: Representative Salaries {#appendix-2-representative-salaries}

+------------------------+---------------+-------------+-------------+-------------+
| Data Analyst           |               |             |             |             |
+:=======================+===============+=============+=============+=============+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \$ 127,790.00 | \           | \$2,458.00  | \$61.00     |
|                        |               | \$10,649.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \$ 102,900.00 | \$8,575.00  | \$1,979.00  | \$49.00     |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \             | \$7,303.00  | \$1,685.00  | \$42.00     |
|                        | \$87,640.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \             | \$5,525.00  | \$1,275.00  | \$32.00     |
|                        | \$66,300.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Data Engineer          |               |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \$ 171,801.00 | \           | \$3,303.00  | \$83.00     |
|                        |               | \$14,316.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \$ 145,800.00 | \           | \$2,803.00  | \$70.00     |
|                        |               | \$12,150.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \$ 138,279.00 | \           | \$2,659.00  | \$66.00     |
|                        |               | \$11,523.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \$ 121,400.00 | \           | \$2,334.00  | \$58.00     |
|                        |               | \$10,116.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Database Administrator |               |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \$ 150,061.00 | \           | \$2,886.00  | \$72.00     |
|                        |               | \$12,505.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \$ 130,400.00 | \           | \$2,508.00  | \$63.00     |
|                        |               | \$10,867.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \$ 108,448.00 | \$9,037.00  | \$2,086.00  | \$52.00     |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \             | \$7,067.00  | \$1,631.00  | \$41.00     |
|                        | \$84,800.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Director of Operations |               |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \$ 171,801.00 | \           | \$3,303.00  | \$83.00     |
|                        |               | \$14,316.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \$ 143,700.00 | \           | \$2,763.00  | \$69.00     |
|                        |               | \$11,975.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \$ 102,922.00 | \$8,576.00  | \$1,979.00  | \$49.00     |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \             | \$6,675.00  | \$1,540.00  | \$39.00     |
|                        | \$80,100.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Grant Writer           |               |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \             | \$7,644.00  | \$1,764.00  | \$44.00     |
|                        | \$91,733.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \             | \$6,492.00  | \$1,498.00  | \$37.00     |
|                        | \$77,900.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \             | \$5,842.00  | \$1,348.00  | \$34.00     |
|                        | \$70,107.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \             | \$4,592.00  | \$1,060.00  | \$26.00     |
|                        | \$55,100.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Director of Operations |               |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \$ 171,801.00 | \           | \$3,303.00  | \$83.00     |
|                        |               | \$14,316.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \$ 143,700.00 | \           | \$2,763.00  | \$69.00     |
|                        |               | \$11,975.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \$ 102,922.00 | \$8,576.00  | \$1,979.00  | \$49.00     |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \             | \$6,675.00  | \$1,540.00  | \$39.00     |
|                        | \$80,100.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Operations Manager     |               |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \$ 115,064.00 | \$9,588.00  | \$2,212.00  | \$55.00     |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \             | \$6,850.00  | \$1,580.00  | \$40.00     |
|                        | \$82,200.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \             | \$5,708.00  | \$1,317.00  | \$33.00     |
|                        | \$68,498.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \             | \$3,625.00  | \$836.00    | \$21.00     |
|                        | \$43,500.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Policy Analyst         |               |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \$ 123,548.00 | \           | \$2,375.00  | \$59.00     |
|                        |               | \$10,295.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \$ 123,500.00 | \           | \$2,375.00  | \$59.00     |
|                        |               | \$10,291.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \             | \$8,122.00  | \$1,874.00  | \$47.00     |
|                        | \$97,464.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \             | \$7,333.00  | \$1,692.00  | \$42.00     |
|                        | \$88,000.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Research Associate     |               |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \             | \$7,910.00  | \$1,825.00  | \$46.00     |
|                        | \$94,915.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \             | \$6,808.00  | \$1,571.00  | \$39.00     |
|                        | \$81,700.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \             | \$5,982.00  | \$1,380.00  | \$35.00     |
|                        | \$71,781.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \             | \$4,817.00  | \$1,112.00  | \$28.00     |
|                        | \$57,800.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Senior Manager         |               |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \$ 178,695.00 | \           | \$3,436.00  | \$86.00     |
|                        |               | \$14,891.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \$ 144,800.00 | \           | \$2,784.00  | \$70.00     |
|                        |               | \$12,066.00 |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \             | \$7,812.00  | \$1,802.00  | \$45.00     |
|                        | \$93,748.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \             | \$4,333.00  | \$1,000.00  | \$25.00     |
|                        | \$52,000.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Website Designer       |               |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \$ 109,232.00 | \$9,103.00  | \$2,101.00  | \$53.00     |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \             | \$7,067.00  | \$1,631.00  | \$41.00     |
|                        | \$84,800.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \             | \$6,436.00  | \$1,485.00  | \$37.00     |
|                        | \$77,227.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \             | \$4,725.00  | \$1,090.00  | \$27.00     |
|                        | \$56,700.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| Website Programmer     |               |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
|                        | Annual Salary | Monthly Pay | Weekly Pay  | Hourly Wage |
+------------------------+---------------+-------------+-------------+-------------+
| Top Earners            | \$ 119,306.00 | \$9,942.00  | \$2,294.00  | \$57.00     |
+------------------------+---------------+-------------+-------------+-------------+
| 75th Percentile        | \$ 100,700.00 | \$8,392.00  | \$1,937.00  | \$48.00     |
+------------------------+---------------+-------------+-------------+-------------+
| Average                | \             | \$7,091.00  | \$1,636.00  | \$41.00     |
|                        | \$85,087.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+
| 25th Percentile        | \             | \$5,608.00  | \$1,294.00  | \$32.00     |
|                        | \$67,300.00   |             |             |             |
+------------------------+---------------+-------------+-------------+-------------+

# 
